name: 'fire_incidents_dbt'
version: '1.0.0'
config-version: 2

profile: 'fire_incidents_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
# schema-paths: ["models"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"